twitter:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: twitter_app
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAI5tNuYrWMjJWzTiq5V7zL
    accessKeySecret: 
    bucket-name: web-yeshou
  redis:
    host: localhost
    port: 6379
    password: 1145
    database: 10
  rabbitmq:
    host: localhost
    port: 5672
    username: lts114
    password: 114514
    virtual-host: /
