server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${twitter.datasource.driver-class-name}
      url: jdbc:mysql://${twitter.datasource.host}:${twitter.datasource.port}/${twitter.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${twitter.datasource.username}
      password: ${twitter.datasource.password}
  data:
    redis:
      host: ${twitter.redis.host}
      password: ${twitter.redis.password}
      port: ${twitter.redis.port}
      database: ${twitter.redis.database}

mybatis-plus:
  type-aliases-package: com.lts.domain.po
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto
      update-strategy: not_null
  mapper-locations: "classpath*:/mapper/**/*.xml"
logging:
  level:
    com:
      lts:
        mapper: debug
        service: info
        controller: info
lts:
    jwt:
      # 设置jwt签名加密时使用的秘钥
      admin-secret-key: itcast114tsts822
      # 设置jwt过期时间
      admin-ttl: 7200000
      # 设置前端传递过来的令牌名称
      admin-token-name: token
      user-secret-key: itheima
      user-ttl: 7200000
      user-token-name: authentication
    alioss:
      endpoint: ${twitter.alioss.endpoint}
      accessKeyId: ${twitterr.alioss.accessKeyId}
      accessKeySecret: ${twitter.alioss.accessKeySecret}
      bucket-name: ${twitter.alioss.bucket-name}